// The 12 Non-Negotiables for OHSC Compliance
// Based on OHSC inspection requirements

export const NON_NEGOTIABLES = [
  {
    id: 1,
    title: "Valid Practice License",
    description: "Current facility license and practice registration certificates",
    documentTypes: ["Facility License Certificate", "Practice Registration Certificate (HPCSA)"],
    category: "Licenses",
    icon: "Award",
  },
  {
    id: 2,
    title: "Professional Registrations",
    description: "All clinical staff have valid HPCSA/SANC registration",
    category: "Staff",
    icon: "UserCheck",
    checkType: "staff_registration" as const,
  },
  {
    id: 3,
    title: "Infection Prevention & Control",
    description: "IPC policy and evidence of implementation (hand hygiene, waste management)",
    documentTypes: ["Infection Prevention & Control (IPC) Policy", "SOP: Decontamination Processes"],
    category: "Policies",
    icon: "Shield",
  },
  {
    id: 4,
    title: "Waste Management",
    description: "Waste management policy, segregation, and valid SLA with waste contractor",
    documentTypes: ["Waste Management Policy", "SOP: Waste Management", "Service Level Agreements with Contractors (Waste, Decontamination, etc.)"],
    category: "Safety",
    icon: "Trash2",
  },
  {
    id: 5,
    title: "Complaints Management",
    description: "Complaints policy, register, and evidence of timely acknowledgement",
    documentTypes: ["Complaints Management Policy", "SOP: Complaints Management"],
    category: "Registers",
    icon: "MessageSquare",
    checkType: "complaints" as const,
  },
  {
    id: 6,
    title: "Fire Safety",
    description: "Fire safety certificate, evacuation plan, and regular drills",
    documentTypes: ["Fire Safety Compliance Certificate", "Fire Safety & Evacuation Plan"],
    category: "Safety",
    icon: "Flame",
  },
  {
    id: 7,
    title: "Emergency Equipment",
    description: "Functional emergency trolley with weekly checklists",
    documentTypes: ["Emergency Equipment Weekly Checklists"],
    category: "Equipment",
    icon: "Activity",
    checkType: "tasks" as const,
    taskNames: ["Emergency Equipment/Trolley Check"],
  },
  {
    id: 8,
    title: "Medicine Management",
    description: "Medicine management policy and temperature monitoring logs",
    documentTypes: ["Medicine Management Policy"],
    category: "Clinical",
    icon: "Pill",
    checkType: "tasks" as const,
    taskNames: ["Temperature Monitoring"],
  },
  {
    id: 9,
    title: "Patient Records",
    description: "Patient records policy, confidentiality, and proper storage",
    documentTypes: ["Patient Records Policy", "Record Storage & Confidentiality Policy", "SOP: Health Records Management"],
    category: "Clinical",
    icon: "FileText",
  },
  {
    id: 10,
    title: "Adverse Events Register",
    description: "Register for tracking and investigating patient safety incidents",
    documentTypes: ["Incident & Adverse Event Register"],
    category: "Registers",
    icon: "AlertTriangle",
    checkType: "adverse_events" as const,
  },
  {
    id: 11,
    title: "Staff Training Records",
    description: "Evidence of BLS, IPC, and H&S training for all staff",
    documentTypes: ["Staff Training Records (BLS, IPC, H&S)"],
    category: "Staff",
    icon: "GraduationCap",
    checkType: "training" as const,
  },
  {
    id: 12,
    title: "Quality Improvement",
    description: "Quality improvement plan, clinical audits, and patient satisfaction surveys",
    documentTypes: ["Quality Improvement Plan", "Clinical Audits (File Audits, Prescribing Audits)", "Patient Satisfaction Surveys & Analysis"],
    category: "Quality",
    icon: "TrendingUp",
  },
];

export type NonNegotiable = (typeof NON_NEGOTIABLES)[number];
