import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | VeriMedrix",
  description: "Terms and conditions for using VeriMedrix compliance management platform.",
};

export default function TermsPage() {
  return (
    <article className="prose prose-slate max-w-none prose-headings:scroll-mt-20">
      <h1 className="text-3xl font-bold mb-2">Terms & Conditions</h1>
      <p className="text-slate-500 text-sm mb-8">
        Last updated: {new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <div className="bg-slate-50 border border-slate-200 rounded-lg p-6 mb-8">
        <p className="text-slate-700 m-0">
          Welcome to VeriMedrix. These Terms and Conditions govern your use of our website and services.
          By accessing or using the Service, you agree to be bound by these Terms.
        </p>
      </div>

      {/* Section 1 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">1. Introduction</h2>
        <p>
          VeriMedrix is a compliance management platform designed for healthcare practices in South Africa,
          helping them manage OHSC (Office of Health Standards Compliance) documentation, tasks, and regulatory requirements.
        </p>
        <p>
          If you disagree with any part of the terms, you may not access the Service.
        </p>
      </section>

      {/* Section 2 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">2. Definitions</h2>
        <ul className="space-y-2">
          <li><strong>&quot;Service&quot;</strong> — the VeriMedrix website, application, and all related services.</li>
          <li><strong>&quot;User&quot;</strong> — any individual or entity that accesses or uses the Service.</li>
          <li><strong>&quot;Practice&quot;</strong> — the healthcare practice or organization using the Service.</li>
          <li><strong>&quot;Content&quot;</strong> — any data, documents, or information uploaded to or generated by the Service.</li>
          <li><strong>&quot;Subscription&quot;</strong> — the paid plan selected by the User to access the Service.</li>
        </ul>
      </section>

      {/* Section 3 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">3. Account Registration</h2>
        <p>To use certain features of the Service, you must register for an account. You agree to:</p>
        <ul className="space-y-2 mt-4">
          <li>Provide accurate, current, and complete information during registration</li>
          <li>Maintain and promptly update your account information</li>
          <li>Keep your password secure and confidential</li>
          <li>Accept responsibility for all activities that occur under your account</li>
          <li>Notify us immediately of any unauthorized use of your account</li>
        </ul>
      </section>

      {/* Section 4 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">4. Subscription and Payment</h2>

        <h3 className="text-lg font-medium mt-6 mb-3">4.1 Subscription Plans</h3>
        <p>VeriMedrix offers various subscription plans with different features and pricing:</p>
        <ul className="space-y-2 mt-4">
          <li>HR Management — R999/month</li>
          <li>OHSC Essential — R1,999/month</li>
          <li>OHSC Professional — R4,999/month</li>
        </ul>

        <h3 className="text-lg font-medium mt-6 mb-3">4.2 Free Trial</h3>
        <p>
          We offer a 14-day free trial for new users. No credit card is required to start a trial.
          At the end of the trial period, you will need to subscribe to continue using the Service.
        </p>

        <h3 className="text-lg font-medium mt-6 mb-3">4.3 Billing</h3>
        <p>
          Subscriptions are billed monthly in South African Rand (ZAR). Payment is processed through
          our payment provider, Paddle. By subscribing, you authorize us to charge your payment method
          on a recurring basis until you cancel.
        </p>

        <h3 className="text-lg font-medium mt-6 mb-3">4.4 Price Changes</h3>
        <p>
          We reserve the right to modify subscription prices with 30 days advance notice. Price changes
          will not affect the current billing cycle.
        </p>
      </section>

      {/* Section 5 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="space-y-2 mt-4">
          <li>Use the Service for any unlawful purpose</li>
          <li>Upload malicious code, viruses, or harmful content</li>
          <li>Attempt to gain unauthorized access to the Service or other users&apos; accounts</li>
          <li>Interfere with or disrupt the Service or servers</li>
          <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
          <li>Use the Service to store or transmit infringing, defamatory, or otherwise unlawful content</li>
          <li>Resell, sublicense, or redistribute the Service without authorization</li>
        </ul>
      </section>

      {/* Section 6 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">6. Data and Privacy</h2>

        <h3 className="text-lg font-medium mt-6 mb-3">6.1 Your Data</h3>
        <p>
          You retain ownership of all Content you upload to the Service. By using the Service, you grant
          us a limited license to store, process, and display your Content as necessary to provide the Service.
        </p>

        <h3 className="text-lg font-medium mt-6 mb-3">6.2 Data Protection</h3>
        <p>
          We take data protection seriously and comply with the Protection of Personal Information Act (POPIA).
          Your data is encrypted in transit and at rest using industry-standard encryption protocols.
        </p>

        <h3 className="text-lg font-medium mt-6 mb-3">6.3 Data Backup</h3>
        <p>
          We perform daily backups of all data. However, we recommend you maintain your own backup copies
          of critical documents.
        </p>
      </section>

      {/* Section 7 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">7. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality are owned by VeriMedrix and are
          protected by international copyright, trademark, and other intellectual property laws.
        </p>
        <p className="mt-4">
          You may not copy, modify, distribute, sell, or lease any part of the Service without our prior written consent.
        </p>
      </section>

      {/* Section 8 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">8. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express
          or implied. We do not warrant that:
        </p>
        <ul className="space-y-2 mt-4">
          <li>The Service will be uninterrupted, timely, secure, or error-free</li>
          <li>The results obtained from using the Service will be accurate or reliable</li>
          <li>Any errors in the Service will be corrected</li>
        </ul>

        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mt-6">
          <p className="text-amber-800 m-0">
            <strong>Important:</strong> VeriMedrix is a compliance management tool and does not provide legal,
            medical, or professional advice. While we help you track compliance requirements, you remain
            responsible for ensuring your practice meets all regulatory requirements.
          </p>
        </div>
      </section>

      {/* Section 9 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">9. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, VeriMedrix shall not be liable for any indirect, incidental,
          special, consequential, or punitive damages, including but not limited to:
        </p>
        <ul className="space-y-2 mt-4">
          <li>Loss of profits, data, business opportunities, or goodwill</li>
          <li>Your use or inability to use the Service</li>
          <li>Any unauthorized access to or alteration of your Content</li>
          <li>Any third-party conduct on the Service</li>
          <li>Any regulatory penalties or compliance failures</li>
        </ul>
        <p className="mt-4">
          Our total liability for any claims arising from the Service shall not exceed the amount you paid
          for the Service in the 12 months preceding the claim.
        </p>
      </section>

      {/* Section 10 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">10. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless VeriMedrix, its officers, directors, employees, and agents
          from any claims, damages, losses, or expenses (including reasonable legal fees) arising from:
        </p>
        <ul className="space-y-2 mt-4">
          <li>Your use of the Service</li>
          <li>Your violation of these Terms</li>
          <li>Your violation of any third-party rights</li>
          <li>Your Content</li>
        </ul>
      </section>

      {/* Section 11 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">11. Termination</h2>

        <h3 className="text-lg font-medium mt-6 mb-3">11.1 By You</h3>
        <p>
          You may cancel your subscription at any time through your account settings or by contacting support.
          Cancellation will take effect at the end of your current billing period.
        </p>

        <h3 className="text-lg font-medium mt-6 mb-3">11.2 By Us</h3>
        <p>We may suspend or terminate your account immediately if you:</p>
        <ul className="space-y-2 mt-4">
          <li>Breach these Terms</li>
          <li>Fail to pay subscription fees</li>
          <li>Engage in fraudulent or illegal activity</li>
        </ul>

        <h3 className="text-lg font-medium mt-6 mb-3">11.3 Effect of Termination</h3>
        <p>
          Upon termination, you will lose access to the Service and your Content. We will retain your data
          for 30 days after termination, during which you may request an export of your data.
        </p>
      </section>

      {/* Section 12 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">12. Modifications to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will provide notice of material changes
          via email or through the Service.
        </p>
        <p className="mt-4">
          Your continued use of the Service after such changes constitutes acceptance of the modified Terms.
        </p>
      </section>

      {/* Section 13 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">13. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the Republic of
          South Africa.
        </p>
        <p className="mt-4">
          Any disputes arising from these Terms shall be subject to the exclusive jurisdiction
          of the courts of South Africa.
        </p>
      </section>

      {/* Section 14 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">14. Severability</h2>
        <p>
          If any provision of these Terms is found to be unenforceable, the remaining provisions shall
          continue in full force and effect.
        </p>
      </section>

      {/* Section 15 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold border-b pb-2 mb-4">15. Contact Information</h2>
        <p>If you have any questions about these Terms, please contact us:</p>
        <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 mt-4">
          <p className="m-0"><strong>Email:</strong> admin@verimedrix.com</p>
          <p className="m-0 mt-2"><strong>Website:</strong> verimedrix.com</p>
        </div>
      </section>
    </article>
  );
}
